export const fakeData = [
  { brand: "Apple", name: "iPhone 15", description: "A high-quality product from Apple.", image: "https://picsum.photos/seed/picsum/200/300" },
  { brand: "Apple", name: "MacBook Pro", description: "An innovative product by Apple.", image: "https://picsum.photos/seed/picsum/200/300" },
  { brand: "Apple", name: "iPad Air", description: "A reliable product from Apple.", image: "https://picsum.photos/seed/picsum/200/300" },
  { brand: "Apple", name: "Apple Watch Series 9", description: "A stylish product by Apple.", image: "https://picsum.photos/seed/picsum/200/300" },
  { brand: "Apple", name: "AirPods Pro", description: "A durable product from Apple.", image: "https://picsum.photos/seed/picsum/200/300" },
  { brand: "Apple", name: "Apple TV 4K", description: "A versatile product by Apple.", image: "https://picsum.photos/seed/picsum/200/300" },
  { brand: "Samsung", name: "Galaxy S23", description: "A premium product from Samsung.", image: "https://picsum.photos/seed/picsum/200/300" },
  { brand: "Samsung", name: "Galaxy Z Fold 5", description: "A cutting-edge product by Samsung.", image: "https://picsum.photos/seed/picsum/200/300" },
  { brand: "Samsung", name: "Galaxy Tab S9", description: "A trusted product from Samsung.", image: "https://picsum.photos/seed/picsum/200/300" },
  { brand: "Samsung", name: "Galaxy Watch 6", description: "A popular product by Samsung.", image: "https://picsum.photos/seed/picsum/200/300" },
  { brand: "Samsung", name: "Galaxy Buds 2 Pro", description: "A well-designed product from Samsung.", image: "https://picsum.photos/seed/picsum/200/300" },
  { brand: "Samsung", name: "Samsung Smart TV", description: "A high-performance product by Samsung.", image: "https://picsum.photos/seed/picsum/200/300" },
  { brand: "Google", name: "Pixel 8", description: "A cost-effective product from Google.", image: "https://picsum.photos/seed/picsum/200/300" },
  { brand: "Google", name: "Pixel Tablet", description: "A user-friendly product by Google.", image: "https://picsum.photos/seed/picsum/200/300" },
  { brand: "Google", name: "Nest Hub Max", description: "A compact product from Google.", image: "https://picsum.photos/seed/picsum/200/300" },
  { brand: "Google", name: "Pixel Watch", description: "A lightweight product by Google.", image: "https://picsum.photos/seed/picsum/200/300" },
  { brand: "Google", name: "Nest Thermostat", description: "A durable and efficient product from Google.", image: "https://picsum.photos/seed/picsum/200/300" },
  { brand: "Google", name: "Chromecast Ultra", description: "A sleek product by Google.", image: "https://picsum.photos/seed/picsum/200/300" },
  { brand: "Ford", name: "F-150 Lightning", description: "A powerful product from Ford.", image: "https://picsum.photos/seed/picsum/200/300" },
  { brand: "Ford", name: "Mustang Mach-E", description: "A modern product by Ford.", image: "https://picsum.photos/seed/picsum/200/300" },
  { brand: "Ford", name: "Bronco Sport", description: "A dependable product from Ford.", image: "https://picsum.photos/seed/picsum/200/300" },
  { brand: "Ford", name: "Explorer Hybrid", description: "A feature-rich product by Ford.", image: "https://picsum.photos/seed/picsum/200/300" },
  { brand: "Ford", name: "Ranger Raptor", description: "A high-tech product from Ford.", image: "https://picsum.photos/seed/picsum/200/300" },
  { brand: "Ford", name: "Transit Connect", description: "A robust product by Ford.", image: "https://picsum.photos/seed/picsum/200/300" },
  { brand: "Toyota", name: "Corolla Cross", description: "A compact and efficient product from Toyota.", image: "https://picsum.photos/seed/picsum/200/300" },
  { brand: "Toyota", name: "Camry Hybrid", description: "A stylish and affordable product by Toyota.", image: "https://picsum.photos/seed/picsum/200/300" },
  { brand: "Toyota", name: "RAV4 Prime", description: "A reliable and innovative product from Toyota.", image: "https://picsum.photos/seed/picsum/200/300" },
  { brand: "Toyota", name: "Highlander Platinum", description: "A premium and durable product by Toyota.", image: "https://picsum.photos/seed/picsum/200/300" },
  { brand: "Toyota", name: "Tacoma TRD Pro", description: "A cutting-edge and versatile product from Toyota.", image: "https://picsum.photos/seed/picsum/200/300" },
  { brand: "Toyota", name: "Tundra Capstone", description: "A trusted and high-quality product by Toyota.", image: "https://picsum.photos/seed/picsum/200/300" }
];