export const fakeData = [
  { brand: "BrandA", name: "Product1", description: "A high-quality product from BrandA." },
  { brand: "BrandA", name: "Product2", description: "An innovative product by BrandA." },
  { brand: "BrandA", name: "Product3", description: "A reliable product from BrandA." },
  { brand: "BrandA", name: "Product4", description: "A stylish product by BrandA." },
  { brand: "BrandA", name: "Product5", description: "A durable product from BrandA." },
  { brand: "BrandA", name: "Product6", description: "A versatile product by BrandA." },
  { brand: "BrandB", name: "Product1", description: "A premium product from BrandB." },
  { brand: "BrandB", name: "Product2", description: "A cutting-edge product by BrandB." },
  { brand: "BrandB", name: "Product3", description: "A trusted product from BrandB." },
  { brand: "BrandB", name: "Product4", description: "A popular product by BrandB." },
  { brand: "BrandB", name: "Product5", description: "A well-designed product from BrandB." },
  { brand: "BrandB", name: "Product6", description: "A high-performance product by BrandB." },
  { brand: "BrandC", name: "Product1", description: "A cost-effective product from BrandC." },
  { brand: "BrandC", name: "Product2", description: "A user-friendly product by BrandC." },
  { brand: "BrandC", name: "Product3", description: "A compact product from BrandC." },
  { brand: "BrandC", name: "Product4", description: "A lightweight product by BrandC." },
  { brand: "BrandC", name: "Product5", description: "A durable and efficient product from BrandC." },
  { brand: "BrandC", name: "Product6", description: "A sleek product by BrandC." },
  { brand: "BrandD", name: "Product1", description: "A powerful product from BrandD." },
  { brand: "BrandD", name: "Product2", description: "A modern product by BrandD." },
  { brand: "BrandD", name: "Product3", description: "A dependable product from BrandD." },
  { brand: "BrandD", name: "Product4", description: "A feature-rich product by BrandD." },
  { brand: "BrandD", name: "Product5", description: "A high-tech product from BrandD." },
  { brand: "BrandD", name: "Product6", description: "A robust product by BrandD." },
  { brand: "BrandE", name: "Product1", description: "A compact and efficient product from BrandE." },
  { brand: "BrandE", name: "Product2", description: "A stylish and affordable product by BrandE." },
  { brand: "BrandE", name: "Product3", description: "A reliable and innovative product from BrandE." },
  { brand: "BrandE", name: "Product4", description: "A premium and durable product by BrandE." },
  { brand: "BrandE", name: "Product5", description: "A cutting-edge and versatile product from BrandE." },
  { brand: "BrandE", name: "Product6", description: "A trusted and high-quality product by BrandE." }
];
