export const fakeData = [
  { brand: "Apple", name: "Product1", description: "A high-quality product from Apple." },
  { brand: "Apple", name: "Product2", description: "An innovative product by Apple." },
  { brand: "Apple", name: "Product3", description: "A reliable product from Apple." },
  { brand: "Apple", name: "Product4", description: "A stylish product by Apple." },
  { brand: "Apple", name: "Product5", description: "A durable product from Apple." },
  { brand: "Apple", name: "Product6", description: "A versatile product by Apple." },
  { brand: "Samsung", name: "Product1", description: "A premium product from Samsung." },
  { brand: "Samsung", name: "Product2", description: "A cutting-edge product by Samsung." },
  { brand: "Samsung", name: "Product3", description: "A trusted product from Samsung." },
  { brand: "Samsung", name: "Product4", description: "A popular product by Samsung." },
  { brand: "Samsung", name: "Product5", description: "A well-designed product from Samsung." },
  { brand: "Samsung", name: "Product6", description: "A high-performance product by Samsung." },
  { brand: "Google", name: "Product1", description: "A cost-effective product from Google." },
  { brand: "Google", name: "Product2", description: "A user-friendly product by Google." },
  { brand: "Google", name: "Product3", description: "A compact product from Google." },
  { brand: "Google", name: "Product4", description: "A lightweight product by Google." },
  { brand: "Google", name: "Product5", description: "A durable and efficient product from Google." },
  { brand: "Google", name: "Product6", description: "A sleek product by Google." },
  { brand: "Ford", name: "Product1", description: "A powerful product from Ford." },
  { brand: "Ford", name: "Product2", description: "A modern product by Ford." },
  { brand: "Ford", name: "Product3", description: "A dependable product from Ford." },
  { brand: "Ford", name: "Product4", description: "A feature-rich product by Ford." },
  { brand: "Ford", name: "Product5", description: "A high-tech product from Ford." },
  { brand: "Ford", name: "Product6", description: "A robust product by Ford." },
  { brand: "Toyota", name: "Product1", description: "A compact and efficient product from Toyota." },
  { brand: "Toyota", name: "Product2", description: "A stylish and affordable product by Toyota." },
  { brand: "Toyota", name: "Product3", description: "A reliable and innovative product from Toyota." },
  { brand: "Toyota", name: "Product4", description: "A premium and durable product by Toyota." },
  { brand: "Toyota", name: "Product5", description: "A cutting-edge and versatile product from Toyota." },
  { brand: "Toyota", name: "Product6", description: "A trusted and high-quality product by Toyota." }
];
